Refactorcode
KBS-Webshop/KBS-Webshop pull request #43
Opened 2024-01-04 19:29 UTC by samberkhout

2024-01-05 10:29 UTC, RenzeBoerman commented on orderbevestiging.php
> +    $editorContent=$content;
Als je de code netter wil maken zal ik ervoor kiezen om dit anders te doen
`$editorReplacing = [
    "$(naam)" => $naam,
    "$(customerID)" => $customerID
];
return str_replace(array_keys($editorReplacing), array_values($editorReplacing), $content);
`

2024-01-05 10:32 UTC, RenzeBoerman commented on orderbevestiging.php
> + * @param $telefoonnummer
Nice dat je een docstring gebruikt maar voegt het echt wat toe? En waar heb je dit vandaan als het chatgpt of iets is zal ik ook nog even nadenken of je dit erin wilt zetten.

2024-01-07 20:18 UTC, chrisivkina commented on orderbevestiging.php
> +function getEditorContent($content, $naam, $customerID, $telefoonnummer, $bezorgAdres, $postcode, string $linkUserInfo, string $logo){
Ik raad aan een andere functienaam te kiezen. Bijvoorbeeld parseEditorContent.

2024-01-07 20:31 UTC, chrisivkina requested changes
ik kan niet bestaande templates aanpassen

2024-01-07 20:35 UTC, merged